version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: your_database_name
      POSTGRES_USER: your_database_user
      POSTGRES_PASSWORD: your_database_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./backend
    environment:
      DATABASE_URL: postgres://your_database_user:your_database_password@postgres:5432/your_database_name
    depends_on:
      - postgres
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./budget-frontend
    ports:
      - "3000:3000"

volumes:
  postgres_data: