"""add_is_draft_to_category_limits

Revision ID: 0c0bd66a0223
Revises: dac3332d8b5b
Create Date: 2025-05-27 12:20:48.388532

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c0bd66a0223'
down_revision: Union[str, None] = 'dac3332d8b5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add column as nullable first
    op.add_column('category_limits', sa.Column('is_draft', sa.Boolean(), nullable=True))
    
    # Set default value for existing records (they are not drafts)
    op.execute("UPDATE category_limits SET is_draft = false WHERE is_draft IS NULL")
    
    # Now make the column non-nullable
    op.alter_column('category_limits', 'is_draft', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('category_limits', 'is_draft')
    # ### end Alembic commands ###
