"""update category limit model

Revision ID: 75bf97c0dc9c
Revises: dd75bb2f2819
Create Date: 2025-02-20 10:11:12.981012

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75bf97c0dc9c'
down_revision: Union[str, None] = 'dd75bb2f2819'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category_limits', sa.Column('limit', sa.DECIMAL(precision=10, scale=2), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('category_limits', 'limit')
    # ### end Alembic commands ###
