"""make category name unique

Revision ID: a1d60cfdeec6
Revises: 75bf97c0dc9c
Create Date: 2025-02-21 23:05:44.171619

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1d60cfdeec6'
down_revision: Union[str, None] = '75bf97c0dc9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('_category_name_user_uc', 'categories', ['name', 'user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('_category_name_user_uc', 'categories', type_='unique')
    # ### end Alembic commands ###
