"""main categories

Revision ID: a2e2abd34497
Revises: 204cac16c777
Create Date: 2025-04-23 14:01:19.234965

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2e2abd34497'
down_revision: Union[str, None] = '204cac16c777'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('main_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'user_id', name='_main_category_name_user_uc')
    )
    op.create_index(op.f('ix_main_categories_id'), 'main_categories', ['id'], unique=False)
    op.create_table('category_main_category',
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('main_category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['main_category_id'], ['main_categories.id'], ),
    sa.PrimaryKeyConstraint('category_id', 'main_category_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('category_main_category')
    op.drop_index(op.f('ix_main_categories_id'), table_name='main_categories')
    op.drop_table('main_categories')
    # ### end Alembic commands ###
