"""Add transaction filter rules

Revision ID: b344c9a9e051
Revises: a2e2abd34497
Create Date: 2025-04-25 14:50:42.231797

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b344c9a9e051'
down_revision: Union[str, None] = 'a2e2abd34497'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transaction_filter_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('description_pattern', sa.String(), nullable=True),
    sa.Column('merchant_name', sa.String(), nullable=True),
    sa.Column('min_amount', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('max_amount', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('description_pattern IS NOT NULL OR merchant_name IS NOT NULL OR min_amount IS NOT NULL OR max_amount IS NOT NULL', name='check_at_least_one_filter_criterion'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'description_pattern', name='_user_desc_filter_uc'),
    sa.UniqueConstraint('user_id', 'merchant_name', name='_user_merchant_filter_uc')
    )
    op.create_index('ix_filter_rules_user_id', 'transaction_filter_rules', ['user_id'], unique=False)
    op.create_index(op.f('ix_transaction_filter_rules_id'), 'transaction_filter_rules', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transaction_filter_rules_id'), table_name='transaction_filter_rules')
    op.drop_index('ix_filter_rules_user_id', table_name='transaction_filter_rules')
    op.drop_table('transaction_filter_rules')
    # ### end Alembic commands ###
