"""Add TrueLayer integration

Revision ID: c4cf929f049e
Revises: a1d60cfdeec6
Create Date: 2025-03-18 10:55:29.676210

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4cf929f049e'
down_revision: Union[str, None] = 'a1d60cfdeec6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bank_connections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider_id', sa.String(), nullable=True),
    sa.Column('provider_name', sa.String(), nullable=True),
    sa.Column('access_token', sa.String(), nullable=True),
    sa.Column('refresh_token', sa.String(), nullable=True),
    sa.Column('token_expires_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bank_connections_id'), 'bank_connections', ['id'], unique=False)
    op.add_column('transactions', sa.Column('bank_transaction_id', sa.String(), nullable=True))
    op.add_column('transactions', sa.Column('account_name', sa.String(), nullable=True))
    op.add_column('transactions', sa.Column('merchant_name', sa.String(), nullable=True))
    op.add_column('transactions', sa.Column('transaction_type', sa.String(), nullable=True))
    op.add_column('transactions', sa.Column('bank_connection_id', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'transactions', ['bank_transaction_id'])
    op.create_foreign_key(None, 'transactions', 'bank_connections', ['bank_connection_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_constraint(None, 'transactions', type_='unique')
    op.drop_column('transactions', 'bank_connection_id')
    op.drop_column('transactions', 'transaction_type')
    op.drop_column('transactions', 'merchant_name')
    op.drop_column('transactions', 'account_name')
    op.drop_column('transactions', 'bank_transaction_id')
    op.drop_index(op.f('ix_bank_connections_id'), table_name='bank_connections')
    op.drop_table('bank_connections')
    # ### end Alembic commands ###
