"""add vault

Revision ID: dac3332d8b5b
Revises: b344c9a9e051
Create Date: 2025-05-14 09:50:15.614458

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dac3332d8b5b'
down_revision: Union[str, None] = 'b344c9a9e051'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create vaults table
    op.create_table('vaults',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vaults_id'), 'vaults', ['id'], unique=False)

    # Alter transaction_type column using a temporary column
    transaction_type_enum = sa.Enum('CASH', 'DIGITAL', name='transactiontype')
    transaction_type_enum.create(op.get_bind(), checkfirst=True)

    op.add_column('transactions', sa.Column('transaction_type_new', transaction_type_enum, nullable=True))
    op.execute(
        "UPDATE transactions SET transaction_type_new = transaction_type::transactiontype "
        "WHERE transaction_type IN ('CASH', 'DIGITAL')"
    )
    op.drop_column('transactions', 'transaction_type')
    op.alter_column('transactions', 'transaction_type_new', new_column_name='transaction_type')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Revert transaction_type column to VARCHAR
    op.add_column('transactions', sa.Column('transaction_type_new', sa.VARCHAR(), nullable=True))
    op.execute(
        "UPDATE transactions SET transaction_type_new = transaction_type::VARCHAR "
        "WHERE transaction_type IN ('CASH', 'DIGITAL')"
    )
    op.drop_column('transactions', 'transaction_type')
    op.alter_column('transactions', 'transaction_type_new', new_column_name='transaction_type')

    transaction_type_enum = sa.Enum('CASH', 'DIGITAL', name='transactiontype')
    transaction_type_enum.drop(op.get_bind(), checkfirst=True)

    # Drop vaults table
    op.drop_index(op.f('ix_vaults_id'), table_name='vaults')
    op.drop_table('vaults')
    # ### end Alembic commands ###
