"""Change transaction amount to DECIMAL

Revision ID: f07f5de5a81c
Revises: 2c67307f8a31
Create Date: 2025-02-13 12:16:23.521217

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f07f5de5a81c'
down_revision: Union[str, None] = '2c67307f8a31'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
