"""update categorization

Revision ID: f68d27d530f1
Revises: 3c1f1de6b86d
Create Date: 2025-04-15 16:54:20.862715

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f68d27d530f1'
down_revision: Union[str, None] = '3c1f1de6b86d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categorization_rules', sa.Column('description_pattern', sa.String(), nullable=True))
    op.alter_column('categorization_rules', 'merchant_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_unique_constraint('_user_description_pattern_uc', 'categorization_rules', ['user_id', 'description_pattern'])
    op.create_index('ix_categorization_rules_user_description', 'categorization_rules', ['user_id', 'description_pattern'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_categorization_rules_user_description', table_name='categorization_rules')
    op.drop_constraint('_user_description_pattern_uc', 'categorization_rules', type_='unique')
    op.alter_column('categorization_rules', 'merchant_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('categorization_rules', 'description_pattern')
    # ### end Alembic commands ###
